
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
from PyQt5.QtCore import QTime, QTimer
import sys
import psutil
import time

class Ui_mainWindow(object):
    
    def comData(self, mainWindow):
        self.com_cpu.setText(str_cpuData)
        self.com_ram.setText(str_ramData)

        if (0.0 < psutil.cpu_percent(1) < 40.0):
            self.com_cpu.setStyleSheet("QLabel { color: green; }")
        elif (40.0 < psutil.cpu_percent(1) < 60.0):
            self.com_cpu.setStyleSheet("QLabel { color: yellow; }")
        elif (60.0 < psutil.cpu_percent(1) < 100.0):
            self.com_cpu.setStyleSheet("QLabel { color: red; }")

        if (0.0 < psutil.virtual_memory()[2] < 40.0):
            self.com_ram.setStyleSheet("QLabel { color: green; }")
        elif (40.0 < psutil.virtual_memory()[2] < 60.0):
            self.com_ram.setStyleSheet("QLabel { color: yellow; }")
        elif (60.0 < psutil.virtual_memory()[2] < 100.0):
            self.com_ram.setStyleSheet("QLabel { color: red; }")   

        print (str_cpuData)
        print (str_ramData)

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(779, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #Set Timer Clock
        self.timer = QTimer()
        self.timer.timeout.connect(self.update)
        self.timer.start(1000)

        #Axis X+
        self.pb_xplus = QtWidgets.QPushButton(self.centralwidget)
        self.pb_xplus.setGeometry(QtCore.QRect(560, 90, 91, 61))
        self.pb_xplus.setObjectName("pb_xplus")
        self.pb_xplus.clicked.connect(self.comData)
        
        #Axis X-
        self.pb_xmin = QtWidgets.QPushButton(self.centralwidget)
        self.pb_xmin.setGeometry(QtCore.QRect(560, 230, 91, 61))
        self.pb_xmin.setObjectName("pb_xmin")
        self.pb_xmin.clicked.connect(self.comData)


        self.pb_yplus = QtWidgets.QPushButton(self.centralwidget)
        self.pb_yplus.setGeometry(QtCore.QRect(660, 160, 91, 61))
        self.pb_yplus.setObjectName("pb_yplus")
        self.pb_ymin = QtWidgets.QPushButton(self.centralwidget)
        self.pb_ymin.setGeometry(QtCore.QRect(460, 160, 91, 61))
        self.pb_ymin.setObjectName("pb_ymin")
        self.pb_zmin = QtWidgets.QPushButton(self.centralwidget)
        self.pb_zmin.setGeometry(QtCore.QRect(460, 90, 91, 61))
        self.pb_zmin.setObjectName("pb_zmin")
        self.pb_zplus = QtWidgets.QPushButton(self.centralwidget)
        self.pb_zplus.setGeometry(QtCore.QRect(660, 90, 91, 61))
        self.pb_zplus.setObjectName("pb_zplus")
        self.pb_yawplus = QtWidgets.QPushButton(self.centralwidget)
        self.pb_yawplus.setGeometry(QtCore.QRect(460, 230, 91, 61))
        self.pb_yawplus.setObjectName("pb_yawplus")
        self.pb_yawmin = QtWidgets.QPushButton(self.centralwidget)
        self.pb_yawmin.setGeometry(QtCore.QRect(660, 230, 91, 61))
        self.pb_yawmin.setObjectName("pb_yawmin")
        self.pb_grip = QtWidgets.QPushButton(self.centralwidget)
        self.pb_grip.setGeometry(QtCore.QRect(560, 160, 91, 61))
        self.pb_grip.setObjectName("pb_grip")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 330, 91, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 360, 91, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 390, 91, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 360, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 330, 71, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cam_list = QtWidgets.QComboBox(self.centralwidget)
        self.cam_list.setGeometry(QtCore.QRect(70, 20, 111, 22))
        self.cam_list.setObjectName("cam_list")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.cam_start = QtWidgets.QPushButton(self.centralwidget)
        self.cam_start.setGeometry(QtCore.QRect(190, 20, 61, 21))
        self.cam_start.setObjectName("cam_start")
        self.cam_stop = QtWidgets.QPushButton(self.centralwidget)
        self.cam_stop.setGeometry(QtCore.QRect(260, 20, 61, 21))
        self.cam_stop.setObjectName("cam_stop")
        self.closeApps = QtWidgets.QPushButton(self.centralwidget)
        self.closeApps.setGeometry(QtCore.QRect(330, 20, 61, 21))
        self.closeApps.setObjectName("closeApps")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 0, 81, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)

        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(550, 0, 81, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)

        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.clock = QtWidgets.QLabel(self.centralwidget)
        self.clock.setGeometry(QtCore.QRect(670, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(24)
        
        self.clock.setFont(font)
        self.clock.setObjectName("clock")
        self.com_cpu = QtWidgets.QLabel(self.centralwidget)
        self.com_cpu.setGeometry(QtCore.QRect(430, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(24)
        self.com_cpu.setFont(font)
        self.com_cpu.setObjectName("com_cpu")
        self.com_ram = QtWidgets.QLabel(self.centralwidget)
        self.com_ram.setGeometry(QtCore.QRect(550, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(24)
        self.com_ram.setFont(font)
        self.com_ram.setObjectName("com_ram")
        self.cam_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.cam_view.setGeometry(QtCore.QRect(20, 80, 381, 201))
        self.cam_view.setObjectName("cam_view")
        self.msgbox = QtWidgets.QListView(self.centralwidget)
        self.msgbox.setGeometry(QtCore.QRect(230, 310, 171, 101))
        self.msgbox.setObjectName("msgbox")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(230, 290, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(410, 60, 16, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 290, 111, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.ob_x = QtWidgets.QLabel(self.centralwidget)
        self.ob_x.setGeometry(QtCore.QRect(80, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.ob_x.setFont(font)
        self.ob_x.setObjectName("ob_x")
        self.ob_y = QtWidgets.QLabel(self.centralwidget)
        self.ob_y.setGeometry(QtCore.QRect(80, 350, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.ob_y.setFont(font)
        self.ob_y.setObjectName("ob_y")
        self.ob_deg = QtWidgets.QLabel(self.centralwidget)
        self.ob_deg.setGeometry(QtCore.QRect(110, 380, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.ob_deg.setFont(font)
        self.ob_deg.setObjectName("ob_deg")
        self.rb_x = QtWidgets.QLabel(self.centralwidget)
        self.rb_x.setGeometry(QtCore.QRect(540, 330, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.rb_x.setFont(font)
        self.rb_x.setObjectName("rb_x")
        self.rb_y = QtWidgets.QLabel(self.centralwidget)
        self.rb_y.setGeometry(QtCore.QRect(540, 360, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.rb_y.setFont(font)
        self.rb_y.setObjectName("rb_y")
        self.rb_z = QtWidgets.QLabel(self.centralwidget)
        self.rb_z.setGeometry(QtCore.QRect(540, 390, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.rb_z.setFont(font)
        self.rb_z.setObjectName("rb_z")
        self.rb_yaw = QtWidgets.QLabel(self.centralwidget)
        self.rb_yaw.setGeometry(QtCore.QRect(690, 330, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.rb_yaw.setFont(font)
        self.rb_yaw.setObjectName("rb_yaw")
        self.rb_gripper = QtWidgets.QLabel(self.centralwidget)
        self.rb_gripper.setGeometry(QtCore.QRect(670, 360, 61, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.rb_gripper.setFont(font)
        self.rb_gripper.setObjectName("rb_gripper")
        self.manual = QtWidgets.QCheckBox(self.centralwidget)
        self.manual.setGeometry(QtCore.QRect(430, 70, 91, 17))
        self.manual.setObjectName("manual")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(430, 300, 111, 16))
        font = QtGui.QFont()
        font.setFamily("ISOCPEUR")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
    
    def update(self, mainWindow):
            self.com_cpu.setText(str_cpuData)
            self.com_ram.setText(str_ramData)
            print (str_cpuData)
            print (str_ramData)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Delta Robot Control Interface System"))
        self.pb_xplus.setText(_translate("mainWindow", "X+"))
        self.pb_xmin.setText(_translate("mainWindow", "X-"))
        self.pb_yplus.setText(_translate("mainWindow", "Y+"))
        self.pb_ymin.setText(_translate("mainWindow", "Y-"))
        self.pb_zmin.setText(_translate("mainWindow", "Z-"))
        self.pb_zplus.setText(_translate("mainWindow", "Z+"))
        self.pb_yawplus.setText(_translate("mainWindow", "YAW+"))
        self.pb_yawmin.setText(_translate("mainWindow", "YAW-"))
        self.pb_grip.setText(_translate("mainWindow", "Gripper"))
        self.label_2.setText(_translate("mainWindow", "X Axis    :"))
        self.label_3.setText(_translate("mainWindow", "Y Axis    :"))
        self.label_4.setText(_translate("mainWindow", "Z Axis    :"))
        self.label_5.setText(_translate("mainWindow", "Gripper :"))
        self.label_6.setText(_translate("mainWindow", "YAW Axis :"))
        self.label_7.setText(_translate("mainWindow", "X Axis :"))
        self.label_8.setText(_translate("mainWindow", "Y Axis :"))
        self.label_9.setText(_translate("mainWindow", "Orientation :"))
        self.label_11.setText(_translate("mainWindow", "Camera : "))
        self.cam_start.setText(_translate("mainWindow", "Start"))
        self.cam_stop.setText(_translate("mainWindow", "Stop"))
        self.closeApps.setText(_translate("mainWindow", "Close"))
        self.label_12.setText(_translate("mainWindow", "CPU Usage :"))
        self.label_13.setText(_translate("mainWindow", "RAM Usage :"))
        self.clock.setText(_translate("mainWindow", "12:15:00"))
        self.com_cpu.setText(_translate("mainWindow", "70.0 %"))
        self.com_ram.setText(_translate("mainWindow", "50.0 %"))
        self.label_17.setText(_translate("mainWindow", "Message : "))
        self.label_18.setText(_translate("mainWindow", "Object Location :  : "))
        self.ob_x.setText(_translate("mainWindow", "12"))
        self.ob_y.setText(_translate("mainWindow", "12"))
        self.ob_deg.setText(_translate("mainWindow", "12"))
        self.rb_x.setText(_translate("mainWindow", "12"))
        self.rb_y.setText(_translate("mainWindow", "12"))
        self.rb_z.setText(_translate("mainWindow", "12"))
        self.rb_yaw.setText(_translate("mainWindow", "12"))
        self.rb_gripper.setText(_translate("mainWindow", "ON"))
        self.manual.setText(_translate("mainWindow", "Manual Drive"))
        self.label_26.setText(_translate("mainWindow", "Camera View :"))
        self.label_27.setText(_translate("mainWindow", "Robot Location :  : "))

app = QtWidgets.QApplication(sys.argv)
mainWindow = QtWidgets.QMainWindow()
ui = Ui_mainWindow()
ui.setupUi(mainWindow)
mainWindow.show()
sys.exit(app.exec_())